-- 1. Create the 'posts' table
create table if not exists posts (
  id bigint generated by default as identity primary key,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users(id) not null
);

-- 2. Enable Row Level Security (RLS)
alter table posts enable row level security;

-- 3. Create Policies (Security Rules)

-- Allow users to view their own posts
create policy "Users can view own posts" 
on posts for select 
using ( auth.uid() = user_id );

-- Allow users to insert their own posts
create policy "Users can insert own posts" 
on posts for insert 
with check ( auth.uid() = user_id );

-- Allow users to update their own posts
create policy "Users can update own posts" 
on posts for update 
using ( auth.uid() = user_id );

-- Allow users to delete their own posts
create policy "Users can delete own posts" 
on posts for delete 
using ( auth.uid() = user_id );
