import "./global.css";
// import localFont from 'next/font/local'

// export const pretendard = localFont({
//   src: '../public/fonts/Pretendard-Regular.woff2',
//   display: 'swap'
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  )
}

