import * as SQLite from 'expo-sqlite';
import { Annotation } from '../types';

const db = SQLite.openDatabaseSync('plainpdf.db');

export const initDatabase = () => {
    db.execSync(`
    CREATE TABLE IF NOT EXISTS annotations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      docId TEXT NOT NULL,
      page INTEGER NOT NULL,
      type TEXT NOT NULL,
      data TEXT NOT NULL,
      timestamp REAL NOT NULL
    );
  `);
};

export const saveAnnotation = (annotation: Annotation) => {
    // Check if it exists (by id if we persist it, but for now we generate IDs with Date.now())
    // If we want to update, we need a stable ID.
    // For MVP, let's assume we just insert new ones or replace.
    // But wait, if we load from DB, we have the ID.
    // So we should UPSERT or INSERT.

    // Actually, for MVP, let's just INSERT.
    // But if we edit, we need UPDATE.
    // Let's use INSERT OR REPLACE if we keep IDs consistent.
    // But Date.now() IDs might collide if we are fast? No.

    // However, if we load from DB, the ID is from DB (INTEGER PK).
    // So we should use that ID.
    // If the annotation has an ID that exists in DB, update it.
    // If it's a new annotation (ID generated by Date.now()), insert it.
    // But Date.now() is large integer. SQLite INTEGER is 64-bit usually.

    // Let's just use INSERT for now and assume we don't update existing annotations in this MVP 
    // (except maybe moving them? PRD says "Select and Delete").
    // So we need Delete.

    const { id, docId, page, type, data, timestamp } = annotation;

    // We try to insert. If ID exists, we replace?
    // Since we generate ID on client as Date.now(), it's unique.
    // But when we save to DB, we might want to let DB assign ID?
    // No, let's use client ID for simplicity if it fits in INTEGER.
    // JS numbers are doubles. Date.now() fits in 53 bits (safe integer).

    db.runSync(
        'INSERT OR REPLACE INTO annotations (id, docId, page, type, data, timestamp) VALUES (?, ?, ?, ?, ?, ?)',
        [id, docId, page, type, data, timestamp]
    );
};

export const getAnnotations = (docId: string): Annotation[] => {
    const result = db.getAllSync<Annotation>(
        'SELECT * FROM annotations WHERE docId = ?',
        [docId]
    );
    return result;
};

export const deleteAnnotation = (id: number) => {
    db.runSync('DELETE FROM annotations WHERE id = ?', [id]);
};
