import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header"; // Import the Header component

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`bg-white text-gray-900 antialiased`}
      >
        <Header /> {/* Render the Header component */}
        {children}
      </body>
    </html>
  );
}
